blank_issues_enabled: false
contact_links:
  - name: Preguntas y discusiones
    url: https://github.com/L-51/ugr-tesis/discussions
    about: Por favor, usa la sección de Discussions (Discusiones) para resolver dudas de cómo usar LaTeX o la plantilla.
